AMAS_JGLAHE: amas.AMAS.ParsedArgs Class Reference
amas.AMAS.ParsedArgs Class Reference
Public Member Functions
__init__ (self)
add_common_args (self, parser)
trim (self)
summary (self)
concat (self)
convert (self)
replicate (self)
split (self)
metapartitions (self)
translate (self)
remove (self)
get_args_dict (self)
Public Attributes
args
Detailed Description
Definition at line 50 of file AMAS.py.
Constructor & Destructor Documentation
__init__()
amas.AMAS.ParsedArgs.__init__ (self)
Definition at line 52 of file AMAS.py.
    def __init__(self):
        parser = argparse.ArgumentParser(
            usage='''AMAS <command> [<args>]
The AMAS commands are:
  concat            Concatenate input alignments.
  convert           Convert to other file format.
  replicate         Create replicate data sets for phylogenetic jackknife.
  split             Split alignment according to a partitions file.
  metapartitions    Runs `split` and concatenates the output.
  summary           Write alignment summary.
  remove            Remove taxa from alignment.
  translate         Translate DNA alignment into protein alignment.
  trim              Remove columns from alignment.
Use AMAS <command> -h for help with arguments of the command of interest
'''
        )
        parser.add_argument(
            "command",
            help="Subcommand to run"
        )
        # parse_args defaults to [1:] for args, but you need to
        # exclude the rest of the args too, or validation will fail
        self.args = parser.parse_args(sys.argv[1:2])
        if not hasattr(self, self.args.command):
            print('Unrecognized command')
            parser.print_help()
            exit(1)
        # use dispatch pattern to invoke method with same name
        getattr(self, self.args.command)()
Member Function Documentation
add_common_args()
amas.AMAS.ParsedArgs.add_common_args (self, parser)
Definition at line 87 of file AMAS.py.
    def add_common_args(self, parser):
        # define required arguments for every command
        requiredNamed = parser.add_argument_group('required arguments')
        parser.add_argument(
            "-e",
            "--check-align",
            dest = "check_align",
            action = "store_true",
            default = False,
            help = "Check if input sequences are aligned. Default: no check"
        )
        parser.add_argument(
            # parallelization is used for file parsing and calculating summary stats
            "-c",
            "--cores",
            dest = "cores",
            default = 1,
            help = "Number of cores used. Default: 1"
        )
        requiredNamed.add_argument(
            "-i",
            "--in-files",
            nargs = "+",
            type = str,
            dest = "in_files",
            required = True,
            help = """Alignment files to be taken as input.
            You can specify multiple files using wildcards (e.g. --in-files *fasta)"""
        )
        requiredNamed.add_argument(
            "-f",
            "--in-format",
            dest = "in_format",
            required = True,
            choices = ["fasta", "phylip", "nexus", "phylip-int", "nexus-int"],
            help = "The format of input alignment"
        )
        requiredNamed.add_argument(
            "-d",
            "--data-type",
            dest = "data_type",
            required = True,
            choices = ["aa", "dna"],
            help = "Type of data"
        )
Referenced by amas.AMAS.ParsedArgs.concat(), amas.AMAS.ParsedArgs.convert(), amas.AMAS.ParsedArgs.metapartitions(), amas.AMAS.ParsedArgs.remove(), amas.AMAS.ParsedArgs.replicate(), amas.AMAS.ParsedArgs.split(), amas.AMAS.ParsedArgs.summary(), amas.AMAS.ParsedArgs.translate(), and amas.AMAS.ParsedArgs.trim().
concat()
amas.AMAS.ParsedArgs.concat (self)
Definition at line 201 of file AMAS.py.
    def concat(self):
        # concat command
        parser = argparse.ArgumentParser(
            description="Concatenate input alignments"
        )
        parser.add_argument(
            "-p",
            "--concat-part",
            dest = "concat_part",
            default = "partitions.txt",
            help = "File name for the concatenated alignment partitions. Default: 'partitions.txt'"
        )
        parser.add_argument(
            "-t",
            "--concat-out",
            dest = "concat_out",
            default = "concatenated.out",
            help = "File name for the concatenated alignment. Default: 'concatenated.out'"
        )
        parser.add_argument(
            "-u",
            "--out-format",
            dest = "out_format",
            choices = ["fasta", "phylip", "nexus", "phylip-int", "nexus-int"],
            default = "fasta",
            help = "File format for the output alignment. Default: fasta"
        )
        parser.add_argument(
            "-y",
            "--part-format",
            dest = "part_format",
            choices = ["nexus", "iqtree-nexus", "raxml", "unspecified"],
            default = "unspecified",
            help = "Format of the partitions file. Default: 'unspecified'"
        )
        parser.add_argument(
            "-n",
            "--codons",
            dest = "codons",
            choices = ["none", "12", "123"],
            default = "none",
            help = "Use codon partitioning for 1st and 2nd or all three positions. Default: Don't use"
        )
        # add shared arguments
        self.add_common_args(parser)
        args = parser.parse_args(sys.argv[2:])
        return args
References amas.AMAS.ParsedArgs.add_common_args().
convert()
amas.AMAS.ParsedArgs.convert (self)
Definition at line 249 of file AMAS.py.
    def convert(self):
        # convert command
        parser = argparse.ArgumentParser(
            description="Convert to other file format",
        )
        parser.add_argument(
            "-u",
            "--out-format",
            dest = "out_format",
            choices = ["fasta", "phylip", "nexus", "phylip-int", "nexus-int"],
            default = "fasta",
            help = "File format for the output alignment. Default: fasta"
        )
        # add shared arguments
        self.add_common_args(parser)
        args = parser.parse_args(sys.argv[2:])
        return args
References amas.AMAS.ParsedArgs.add_common_args().
get_args_dict()
amas.AMAS.ParsedArgs.get_args_dict (self)
Definition at line 508 of file AMAS.py.
    def get_args_dict(self):
        # store arguments in a dictionary
        command = self.args.__dict__
        arguments = getattr(self, self.args.command)().__dict__
        argument_dictionary = command.copy()
        argument_dictionary.update(arguments)
        return argument_dictionary
References amas.AMAS.ParsedArgs.args.
metapartitions()
amas.AMAS.ParsedArgs.metapartitions (self)
Definition at line 334 of file AMAS.py.
    def metapartitions(self):
        # metapartitions command
        parser = argparse.ArgumentParser(
            formatter_class=argparse.RawTextHelpFormatter,
            description='''Split alignment according to a partition file, then concatenate the output.'''
            '''\n\nuse case:\n'''
            '''    Some utilities cannot parse partition definitions containing strides (\\) and/or discontinuous ranges.\n'''
            '''    In such case, running `split` + `concat` in separate passes can convert a corresponding (super)alignment it into an\n'''
            '''    equivalent compatible form with contiguous (meta)partitions; this may also require renaming metapartiton alignments\n'''
            '''    and partition file entries in order to remove tags applied by each respective operation.\n\n'''
            '''    `metapartitions` combines these steps into one command, with the options `--prepend` and `--no-mpan`\n'''
            '''    providing additional control over the collated (meta)partition names (see their respective help entries).\n\n'''
            '''    Note: in this mode, the format of the input (super)alignment file determines that of all outputs (-u|--out-format is disabled)!\n\n'''
        )
        parser.add_argument(
            "-p",
            "--concat-part",
            dest = "concat_part",
            default = "metapartitions.txt",
            help = "Partition file(name) for the final concatenated alignment of metapartitions. Default: 'metapartitions.txt'"
        )
        parser.add_argument(
            "-t",
            "--concat-out",
            dest = "concat_out",
            default = "concatenated-meta.out",
            help = "File name for the concatenated alignment of metapartitions. Default: 'concatenated-meta.out'"
        )
        parser.add_argument(
            "-y",
            "--part-format",
            dest = "part_format",
            choices = ["nexus", "iqtree-nexus", "raxml", "unspecified"],
            default = "unspecified",
            help = "Partitions file format for the final concatenated alignment of metapartitions. Default: 'unspecified'"
        )
        parser.add_argument(
            "-l",
            "--split-by",
            dest = "split_by",
            help = "Partition file(name) to be used for splitting the initial concatenated alignment.",
            required = True
        )
        parser.add_argument(
            "-j",
            "--remove-empty",
            dest = "remove_empty",
            action = "store_true",
            default = False,
            help = "Remove taxa with sequences composed of only undetermined characters? Default: Don't remove"
        )
        parser.add_argument(
            "--no-san",
            dest = "no_sup_aln_name",
            action = "store_true",
            default = False,
            help = '''Don't prepend the input (super)alignment filename to the (meta)partition-alignment filenames output by `split`'''
        )
        parser.add_argument(
            "--prepend",
            dest = "prepend_label",
            default = None,
            help = '''Prepend <string> to the partition counter in partition file, e.g.'''
            '''\n            --prepend <string>:  <string>_p001_metapartition_alignment_name = 1-1200 ...'''
            '''\n                Default (None):           p001_metapartition_alignment_name = 1-1200 ...'''
            '''\n--no-mpan + --prepend <string>:  <string>_p001 = 1-1200 ...'''
        )
        parser.add_argument(
            "--no-mpan",
            dest = "no_mpan",
            action = "store_true",
            default = False,
            help = '''Omits (meta)partition alignment names when printing partition file, e.g.'''
            '''\n                     --no-mpan:          p001 = 1-1200 ...'''
            '''\n               Default (False):          p001_metapartition_alignment_name = 1-1200 ...'''
            '''\n--prepend <string> + --no-mpan: <string>_p001 = 1-1200 ...'''
        )
        # add shared arguments
        self.add_common_args(parser)
        args = parser.parse_args(sys.argv[2:])
        return args
References amas.AMAS.ParsedArgs.add_common_args().
remove()
amas.AMAS.ParsedArgs.remove (self)
Definition at line 474 of file AMAS.py.
    def remove(self):
        # remove taxa command
        parser = argparse.ArgumentParser(
            description="Remove taxa from alignment",
        )
        parser.add_argument(
            "-x",
            "--taxa-to-remove",
            nargs = "+",
            type = str,
            dest = "taxa_to_remove",
            help = "Taxon/sequence names to be removed.",
            required = True
        )
        parser.add_argument(
            "-u",
            "--out-format",
            dest = "out_format",
            choices = ["fasta", "phylip", "nexus", "phylip-int", "nexus-int"],
            default = "fasta",
            help = "File format for the output alignment. Default: fasta"
        )
        parser.add_argument(
            "-g",
            "--out-prefix",
            dest = "out_prefix",
            default = "reduced_",
            help = "File name prefix for the concatenated alignment. Default: 'reduced_'"
        )
        # add shared arguments
        self.add_common_args(parser)
        args = parser.parse_args(sys.argv[2:])
        return args
References amas.AMAS.ParsedArgs.add_common_args().
replicate()
amas.AMAS.ParsedArgs.replicate (self)
Definition at line 267 of file AMAS.py.
    def replicate(self):
        # replicate command
        parser = argparse.ArgumentParser(
            description="Create replicate datasets for phylogenetic jackknife",
        )
        parser.add_argument(
            "-r",
            "--rep-aln",
            nargs = 2,
            type = int,
            dest = "replicate_args",
            help = "Create replicate data sets for phylogenetic jackknife [replicates, no alignments for each replicate]",
            required = True
        )
        parser.add_argument(
            "-u",
            "--out-format",
            dest = "out_format",
            choices = ["fasta", "phylip", "nexus", "phylip-int", "nexus-int"],
            default = "fasta",
            help = "File format for the output alignment. Default: fasta"
        )
        # add shared arguments
        self.add_common_args(parser)
        args = parser.parse_args(sys.argv[2:])
        return args
References amas.AMAS.ParsedArgs.add_common_args().
split()
amas.AMAS.ParsedArgs.split (self)
Definition at line 294 of file AMAS.py.
    def split(self):
        # split command
        parser = argparse.ArgumentParser(
            description="Split alignment according to a partitions file",
        )
        parser.add_argument(
            "-l",
            "--split-by",
            dest = "split_by",
            help = "File name for partitions to be used for alignment splitting.",
            required = True
        )
        parser.add_argument(
            "-j",
            "--remove-empty",
            dest = "remove_empty",
            action = "store_true",
            default = False,
            help = "Remove taxa with sequences composed of only undetermined characters? Default: Don't remove"
        )
        parser.add_argument(
            "-u",
            "--out-format",
            dest = "out_format",
            choices = ["fasta", "phylip", "nexus", "phylip-int", "nexus-int"],
            default = "fasta",
            help = "File format for the output alignment. Default: fasta"
        )
        parser.add_argument(
            "--no-san",
            dest = "no_sup_aln_name",
            action = "store_true",
            default = False,
            help = '''Don't prepend the input (super)alignment filename to the partition-alignment filenames output by `split`'''
        )
        # add shared arguments
        self.add_common_args(parser)
        args = parser.parse_args(sys.argv[2:])
        return args
References amas.AMAS.ParsedArgs.add_common_args().
Referenced by amas.AMAS.MetaAlignment.write_metapartitions(), and amas.AMAS.MetaAlignment.write_out().
summary()
amas.AMAS.ParsedArgs.summary (self)
Definition at line 176 of file AMAS.py.
    def summary(self):
       # summary command
        parser = argparse.ArgumentParser(
            description="Write alignment summary",
        )
        parser.add_argument(
            "-o",
            "--summary-out",
            dest = "summary_out",
            default = "summary.txt",
            help = "File name for the alignment summary. Default: 'summary.txt'"
        )
        parser.add_argument(
            "-s",
            "--by-taxon",
            dest = "by_taxon_summary",
            action = "store_true",
            default = False,
            help = "In addition to alignment summary, write by sequence/taxon summaries. Default: Don't write"
        )
        # add shared arguments
        self.add_common_args(parser)
        args = parser.parse_args(sys.argv[2:])
        return args
References amas.AMAS.ParsedArgs.add_common_args().
translate()
amas.AMAS.ParsedArgs.translate (self)
Definition at line 416 of file AMAS.py.
    def translate(self):
        # translate command
        parser = argparse.ArgumentParser(
            formatter_class=argparse.RawTextHelpFormatter,
            description="Translate a protein-coding DNA alignment into amino acids"
        )
        parser.add_argument(
            "-b",
            "--code",
            type = int,
            dest = "genetic_code",
            choices = [1, 2, 3, 4, 5, 6, 9, 10, 11, 12, 13, 14, 16, 21, 22, 23, 24, 25, 26],
            default = 1,
            help = '''\nNCBI genetic code to use (Default: 1):'''
'''
   1. The Standard Code
   2. The Vertebrate Mitochondrial Code
   3. The Yeast Mitochondrial Code
   4. The Mold, Protozoan, and Coelenterate Mitochondrial Code and the Mycoplasma/Spiroplasma Code
   5. The Invertebrate Mitochondrial Code
   6. The Ciliate, Dasycladacean and Hexamita Nuclear Code
   9. The Echinoderm and Flatworm Mitochondrial Code
  10. The Euplotid Nuclear Code
  11. The Bacterial, Archaeal and Plant Plastid Code
  12. The Alternative Yeast Nuclear Code
  13. The Ascidian Mitochondrial Code
  14. The Alternative Flatworm Mitochondrial Code
  16. Chlorophycean Mitochondrial Code
  21. Trematode Mitochondrial Code
  22. Scenedesmus obliquus Mitochondrial Code
  23. Thraustochytrium Mitochondrial Code
  24. Pterobranchia Mitochondrial Code
  25. Candidate Division SR1 and Gracilibacteria Code
  26. Pachysolen tannophilus Nuclear Code\n
'''
        )
        parser.add_argument(
            "-k",
            "--reading-frame",
            type = int,
            dest = "reading_frame",
            choices = [1, 2, 3],
            default = 1,
            help = "Number specifying reading frame; i.e. '2' means codons start at the second character of the alignment. Default: 1",
        )
        parser.add_argument(
            "-u",
            "--out-format",
            dest = "out_format",
            choices = ["fasta", "phylip", "nexus", "phylip-int", "nexus-int"],
            default = "fasta",
            help = "File format for the output alignment. Default: fasta"
        )
        # add shared arguments
        self.add_common_args(parser)
        args = parser.parse_args(sys.argv[2:])
        return args
References amas.AMAS.ParsedArgs.add_common_args().
trim()
amas.AMAS.ParsedArgs.trim (self)
Definition at line 134 of file AMAS.py.
    def trim(self):
        # trim command
        parser = argparse.ArgumentParser(
            formatter_class=argparse.RawDescriptionHelpFormatter,
            description='''Trim alignment by occupancy. Optionally removes sites that are not parsimony informative.'''
            '''\nCAUTION: when running on amino acids stop codons marked with * will be treated as missing data!'''
        )
        parser.add_argument(
            "-u",
            "--out-format",
            dest = "out_format",
            choices = ["fasta", "phylip", "nexus", "phylip-int", "nexus-int"],
            default = "fasta",
            help = "File format for the output alignment. Default: fasta"
        )
        parser.add_argument(
            "-o",
            "--trim-out",
            dest = "trim_out",
            help = "File name for the trimmed alignment when providing a single file as input."
        )
        parser.add_argument(
            "-t",
            "--trim-fraction",
            type = proportion,
            dest = "trim_fraction",
            default = 0.6,
            help = "Columns in the alignments with occupancy lower than this value will be removed. Default: 0.6"
        )
        parser.add_argument(
            "-p",
            "--retain-only-parsimony-sites",
            dest = "parsimony_check",
            action = "store_true",
            default = False,
            help = "Only write parsimony informative columns in trimmed alignment Default: write all columns"
        )
        # add shared arguments
        self.add_common_args(parser)
        args = parser.parse_args(sys.argv[2:])
        return args
References amas.AMAS.ParsedArgs.add_common_args().
Member Data Documentation
args
amas.AMAS.ParsedArgs.args
Definition at line 79 of file AMAS.py.
Referenced by amas.AMAS.ParsedArgs.get_args_dict().
The documentation for this class was generated from the following file:
amas/AMAS.py