AMAS_JGLAHE: amas.AMAS.DNAAlignment Class Reference
amas.AMAS.DNAAlignment Class Reference
Public Member Functions
get_summary (self)
get_taxa_summary (self)
get_atgc_content (self)
get_list_from_atgc (self)
get_atgc_from_parsed (self)
get_atgc_from_seq (self, seq)
Static Public Attributes
list alphabet = ["A", "C", "G", "T", "K", "M", "R", "Y", "S", "W", "B", "V", "H", "D", "X", "N", "O", "-", "?"]
list missing_ambiguous_chars = ["K", "M", "R", "Y", "S", "W", "B", "V", "H", "D", "X", "N", "O", "-", "?"]
list missing_chars = ["X", "N", "O", "-", "?"]
list non_alphabet = ["E", "F", "I", "L", "P", "Q", "J", "Z", ".", "*"]
Detailed Description
Alphabets specific to DNA alignments
Definition at line 1107 of file AMAS.py.
Member Function Documentation
get_atgc_content()
amas.AMAS.DNAAlignment.get_atgc_content (self)
Definition at line 1129 of file AMAS.py.
    def get_atgc_content(self):
        # get AC and GC contents for all sequences
        # AT content is the first element of AT, GC content tuple
        # returned by get_atgc_from_seq()
        atgc_records = self.get_atgc_from_parsed()
        at_content = round(sum(atgc[0] for taxon, atgc in atgc_records) / self.get_taxa_no(), 3)
        gc_content = round(1 - float(at_content), 3)
        atgc_content = [str(at_content), str(gc_content)]
        return atgc_content
References amas.AMAS.DNAAlignment.get_atgc_from_parsed(), and amas.AMAS.Alignment.get_taxa_no().
Referenced by amas.AMAS.DNAAlignment.get_summary().
get_atgc_from_parsed()
amas.AMAS.DNAAlignment.get_atgc_from_parsed (self)
Definition at line 1144 of file AMAS.py.
    def get_atgc_from_parsed(self):
        # get AT and GC contents from parsed alignment dictionary
        # return a list of tuples with taxon name, AT content, and GC content
        return sorted([(taxon, self.get_atgc_from_seq(seq)) for taxon, seq in self.parsed_aln.items()])
References amas.AMAS.DNAAlignment.get_atgc_from_seq(), and amas.AMAS.Alignment.parsed_aln.
Referenced by amas.AMAS.DNAAlignment.get_atgc_content(), and amas.AMAS.DNAAlignment.get_list_from_atgc().
get_atgc_from_seq()
amas.AMAS.DNAAlignment.get_atgc_from_seq (self, seq)
Definition at line 1149 of file AMAS.py.
    def get_atgc_from_seq(self, seq):
        # get AT and GC contents from individual sequences
        at_count = seq.count("A") + seq.count("T") + seq.count("W")
        gc_count = seq.count("G") + seq.count("C") + seq.count("S")
        try:
            at_content = round(at_count / (at_count + gc_count), 3)
            gc_content = round(1 - float(at_content), 3)
        except ZeroDivisionError:
            at_content = 0
            gc_content = 0
        return at_content, gc_content
Referenced by amas.AMAS.DNAAlignment.get_atgc_from_parsed().
get_list_from_atgc()
amas.AMAS.DNAAlignment.get_list_from_atgc (self)
Definition at line 1140 of file AMAS.py.
    def get_list_from_atgc(self):
        records = (atgc for taxon, atgc in self.get_atgc_from_parsed())
        return records
References amas.AMAS.DNAAlignment.get_atgc_from_parsed().
Referenced by amas.AMAS.DNAAlignment.get_taxa_summary().
get_summary()
amas.AMAS.DNAAlignment.get_summary (self)
Definition at line 1115 of file AMAS.py.
    def get_summary(self):
        # get alignment summarry specific to nucleotide
        data = self.summarize_alignment()
        new_data = data + self.get_atgc_content() + list(self.get_char_summary()[1])
        return new_data
References amas.AMAS.DNAAlignment.get_atgc_content(), amas.AMAS.Alignment.get_char_summary(), and amas.AMAS.Alignment.summarize_alignment().
get_taxa_summary()
amas.AMAS.DNAAlignment.get_taxa_summary (self)
Definition at line 1121 of file AMAS.py.
    def get_taxa_summary(self):
        # get per-taxon/sequence alignment summary specific to nucleotides
        data = self.summarize_alignment_by_taxa()
        dna_summary = (data, self.get_list_from_atgc(), self.get_taxon_char_summary())
        zipped_list = list(zip(*dna_summary))
        new_data = [list(data_tupl) + list(atgc) + chars for data_tupl, atgc, chars in zipped_list]
        return new_data
References amas.AMAS.DNAAlignment.get_list_from_atgc(), amas.AMAS.Alignment.get_taxon_char_summary(), and amas.AMAS.Alignment.summarize_alignment_by_taxa().
Member Data Documentation
alphabet
list amas.AMAS.DNAAlignment.alphabet = ["A", "C", "G", "T", "K", "M", "R", "Y", "S", "W", "B", "V", "H", "D", "X", "N", "O", "-", "?"] static
Definition at line 1110 of file AMAS.py.
Referenced by amas.AMAS.Alignment.append_count(), amas.AMAS.Alignment.get_char_summary(), and amas.AMAS.Alignment.get_counts_from_seq().
missing_ambiguous_chars
list amas.AMAS.DNAAlignment.missing_ambiguous_chars = ["K", "M", "R", "Y", "S", "W", "B", "V", "H", "D", "X", "N", "O", "-", "?"] static
Definition at line 1111 of file AMAS.py.
Referenced by amas.AMAS.Alignment.get_site_no_missing_ambiguous().
missing_chars
list amas.AMAS.DNAAlignment.missing_chars = ["X", "N", "O", "-", "?"] static
Definition at line 1112 of file AMAS.py.
Referenced by amas.AMAS.Alignment.get_missing_from_seq(), and amas.AMAS.Alignment.replace_missing().
non_alphabet
list amas.AMAS.DNAAlignment.non_alphabet = ["E", "F", "I", "L", "P", "Q", "J", "Z", ".", "*"] static
Definition at line 1113 of file AMAS.py.
The documentation for this class was generated from the following file:
amas/AMAS.py