AMAS_JGLAHE: amas.AMAS.FileParser Class Reference
amas.AMAS.FileParser Class Reference
Public Member Functions
__init__ (self, in_file)
fasta_parse (self)
phylip_parse (self)
phylip_interleaved_parse (self)
nexus_parse (self)
nexus_interleaved_parse (self)
translate_ambiguous (self, seq)
partitions_parse (self)
Public Attributes
in_file
in_file_lines
Detailed Description
Parse file contents and return sequences and sequence names
Definition at line 538 of file AMAS.py.
Constructor & Destructor Documentation
__init__()
amas.AMAS.FileParser.__init__ (self, in_file)
Definition at line 541 of file AMAS.py.
    def __init__(self, in_file):
        self.in_file = in_file
        with FileHandler(in_file) as handle:
            self.in_file_lines = handle.read().rstrip("\r\n")
Member Function Documentation
fasta_parse()
amas.AMAS.FileParser.fasta_parse (self)
Definition at line 546 of file AMAS.py.
    def fasta_parse(self):
        # use regex to parse names and sequences in sequential fasta files
        matches = re.finditer(
            r"^>(.*[^$])([^>]*)",
            self.in_file_lines, re.MULTILINE
        )
        records = {}
        for match in matches:
            name_match = match.group(1).replace("\n", "")
            seq_match = match.group(2).replace("\n", "").upper()
            seq_match = self.translate_ambiguous(seq_match)
            records[name_match] = seq_match
        return records
References amas.AMAS.FileParser.in_file_lines, and amas.AMAS.FileParser.translate_ambiguous().
nexus_interleaved_parse()
amas.AMAS.FileParser.nexus_interleaved_parse (self)
Definition at line 671 of file AMAS.py.
    def nexus_interleaved_parse(self):
        # use regex to parse names and sequences in sequential nexus files
        # find the matrix block
        matches = re.finditer(
            r"(\s+)?(MATRIX\n|matrix\n|MATRIX\r\n|matrix\r\n)(.*?;)",
            self.in_file_lines, re.DOTALL
        )
        # initiate lists for taxa names and sequence strings on separate lines
        taxa = []
        sequences = []
        # initiate a dictionary for the name:sequence records
        records = {}
        for match in matches:
            matrix_match = match.group(3)
            # get names and sequences from the matrix block
            seq_matches = re.finditer(
                r"^(\s+)?[']?(\S+\s\S+|\S+)[']?\s+([A-Za-z*?.{}-]+)($|\s+\[[0-9]+\]$)",
                matrix_match, re.MULTILINE
            )
            for match in seq_matches:
                name_match = match.group(2)
                if name_match not in taxa:
                    taxa.append(name_match)
                seq_match = match.group(3)
                sequences.append(seq_match)
        # initiate a counter to keep track of sequences strung together
        # from separate lines
        counter = 0
        for taxon_no in range(len(taxa)):
            full_length_sequence = "".join([sequences[index] for index in range(counter,len(sequences),len(taxa))])
            records[taxa[taxon_no]] = self.translate_ambiguous(full_length_sequence).replace("\n", "").upper()
            counter += 1
        return records
References amas.AMAS.FileParser.in_file_lines, and amas.AMAS.FileParser.translate_ambiguous().
nexus_parse()
amas.AMAS.FileParser.nexus_parse (self)
Definition at line 645 of file AMAS.py.
    def nexus_parse(self):
        # use regex to parse names and sequences in sequential nexus files
        # find the matrix block
        matches = re.finditer(
            r"(\s+)?(MATRIX\n|matrix\n|MATRIX\r\n|matrix\r\n)(.*?;)",
            self.in_file_lines, re.DOTALL
        )
        records = {}
        # get names and sequences from the matrix block
        for match in matches:
            matrix_match = match.group(3)
            seq_matches = re.finditer(
                r"^(\s+)?[']?(\S+\s\S+|\S+)[']?\s+([A-Za-z*?.{}-]+)($|\s+\[[0-9]+\]$)",
                matrix_match, re.MULTILINE
            )
            for match in seq_matches:
                name_match = match.group(2).replace("\n", "")
                seq_match = match.group(3).replace("\n", "").upper()
                seq_match = self.translate_ambiguous(seq_match)
                records[name_match] = seq_match
        return records
References amas.AMAS.FileParser.in_file_lines, and amas.AMAS.FileParser.translate_ambiguous().
partitions_parse()
amas.AMAS.FileParser.partitions_parse (self)
Definition at line 731 of file AMAS.py.
    def partitions_parse(self):
        # parse partitions file using regex
        # original: `matches = re.finditer(r"^(\s+)?([^ =]+)[ =]+([\\0-9, -]+)", self.in_file_lines, re.MULTILINE)`
        # new version: more permissive -> handles PartionFinder/RAxML/(IQ-TREE 2)best_scheme.nex format partition files
        matches = re.finditer(
            r"""^[ \t]*                                 # start of line w/ zero-or-more (just) whitespaces/tabs
                (
                 (?P<nexus>charset[ ]+)                 # case 1: (IQ-TREE 2)best_scheme.nex partition directive; partition name
                 |
                 (?P<raxml>[A-Za-z0-9_+\.]+,[ \t]+)     # case 2: RAxML/RAxML-NG model(+other pars); partition name
                )?
                (?P<partition_name>[A-Za-z0-9_\-]+)     # case 3: just partition name (including one that contain residual '-out'/'-meta' suffixes)
                [ ]*=[ ]*                               # whitespace-padded (or unpadded) '=': (IQ-TREE 2)best_scheme.nex compatabiliy
                (?P<numbers>[\\0-9, -]+)                # position ranges w/ stride (multiple intervals; from original regex)
                (?P<nexus_term>[ ]*[;])?                # whitespace-prepended (or unprepended) ';' (nexus terminator)
            """,
            self.in_file_lines,
            re.MULTILINE | re.VERBOSE
        )
        # initiate list to store dictionaries with lists
        # of slice positions as values
        partitions = []
        add_to_partitions = partitions.append
        for match in matches:
            # initiate dictionary of partition name as key
            dict_of_dicts = {}
            # and list of dictionaries with slice positions
            list_of_dicts = []
            add_to_list_of_dicts = list_of_dicts.append
            # get parition name and numbers from parsed partition strings
            partition_name = match.group('partition_name')
            numbers = match.group('numbers')
            # remove any whitespace padding '-' (to be consistent with partition-writing format)
            numbers = re.sub(r"[ ]*-[ ]*", "-", numbers)
            # find all numbers that will be used to parse positions
            positions = re.findall(r"([^ ,]+)", numbers)
            for position in positions:
                # create dictionary for slicing input sequence
                # conditioning on whether positions are represented
                # by range, range with stride, or single number
                pos_dict = {}
                if "-" in position:
                    m = re.search(r"([0-9]+)-([0-9]+)", position)
                    pos_dict["start"] = int(m.group(1)) - 1
                    pos_dict["stop"] = int(m.group(2))
                else:
                    pos_dict["start"] = int(position) - 1
                    pos_dict["stop"] = int(position)
                if "\\" in position:
                    # Note: the value of `N` in `...\N` isn't read: the script simply assumes `N` is consistent with the number of
                    # increments per interval when the alignment is parsed with a stride of 3 (designating each cpos).
                    # E.g. For the partition file:
                    #       ...`1-N\2`
                    #       ...`2-N\2`
                    #       ...`(N+1)-M\2`
                    #       ...`(N+2)-M\2`
                    # 3'cpos are ignored due to the absence of intervals `3-N...`, `(N+3)-M...`, not because the associated stride values are`\2`
                    pos_dict["stride"] = 3
                elif "\\" not in position:
                    pos_dict["stride"] = 1
                add_to_list_of_dicts(pos_dict)
            dict_of_dicts[partition_name] = list_of_dicts
            add_to_partitions(dict_of_dicts)
        return partitions
References amas.AMAS.FileParser.in_file_lines.
phylip_interleaved_parse()
amas.AMAS.FileParser.phylip_interleaved_parse (self)
Definition at line 579 of file AMAS.py.
    def phylip_interleaved_parse(self):
        # use regex to parse names and sequences in interleaved phylip files
        tax_chars_matches = re.finditer(
            r"^(\s+)?([0-9]+)[ \t]+([0-9]+)",
            self.in_file_lines, re.MULTILINE
        )
        name_matches = re.finditer(
            r"^(\s+)?(\S+)[ \t]+[A-Za-z*?.{}-]+",
            self.in_file_lines, re.MULTILINE
        )
        seq_matches = re.finditer(
            r"(^(\s+)?\S+[ \t]+|^)([A-Za-z*?.{}-]+)$",
            self.in_file_lines, re.MULTILINE
        )
        # get number of taxa and chars
        for match in tax_chars_matches:
            tax_match = match.group(2)
            chars_match = match.group(3)
        # initiate lists for taxa names and sequence strings on separate lines
        taxa = []
        sequences = []
        # initiate a dictionary for the name:sequence records
        records = {}
        # initiate a counter to keep track of sequences strung together
        # from separate lines
        counter = 0
        for match in name_matches:
            name_match = match.group(2).replace("\n", "")
            taxa.append(name_match)
        for match in seq_matches:
            seq_match = match.group(3).replace("\n", "").upper()
            seq_match = self.translate_ambiguous(seq_match)
            sequences.append(seq_match)
        # try parsing PHYLUCE-style interleaved phylip
        if len(taxa) != int(tax_match):
            taxa = []
            sequences = []
            matches = re.finditer(
                r"(^(\s+)?(\S+)( ){2,}|^\s+)([ A-Za-z*?.{}-]+)",
                self.in_file_lines, re.MULTILINE
            )
            for match in matches:
                try:
                    name_match = match.group(3).replace("\n", "")
                    taxa.append(name_match)
                except AttributeError:
                    pass
                seq_match = match.group(5).replace("\n", "").upper()
                seq_match = "".join(seq_match.split())
                seq_match = self.translate_ambiguous(seq_match)
                sequences.append(seq_match)
        for taxon_no in range(len(taxa)):
            sequence = ""
            for index in range(counter,len(sequences),len(taxa)):
                sequence += sequences[index]
            records[taxa[taxon_no]] = sequence
            counter += 1
        return records
References amas.AMAS.FileParser.in_file_lines, and amas.AMAS.FileParser.translate_ambiguous().
phylip_parse()
amas.AMAS.FileParser.phylip_parse (self)
Definition at line 562 of file AMAS.py.
    def phylip_parse(self):
        # use regex to parse names and sequences in sequential phylip files
        matches = re.finditer(
            r"^(\s+)?(\S+)\s+([A-Za-z*?.{}-]+)",
            self.in_file_lines, re.MULTILINE
        )
        records = {}
        for match in matches:
            name_match = match.group(2).replace("\n", "")
            seq_match = match.group(3).replace("\n", "").upper()
            seq_match = self.translate_ambiguous(seq_match)
            records[name_match] = seq_match
        return records
References amas.AMAS.FileParser.in_file_lines, and amas.AMAS.FileParser.translate_ambiguous().
translate_ambiguous()
amas.AMAS.FileParser.translate_ambiguous (self, seq)
Definition at line 712 of file AMAS.py.
    def translate_ambiguous(self, seq):
        # translate ambiguous characters from curly bracket format
        # to single letter format
        # also remove spaces from sequences
        seq = seq.replace("{GT}", "K")
        seq = seq.replace("{AC}", "M")
        seq = seq.replace("{AG}", "R")
        seq = seq.replace("{CT}", "Y")
        seq = seq.replace("{CG}", "S")
        seq = seq.replace("{AT}", "W")
        seq = seq.replace("{CGT}", "B")
        seq = seq.replace("{ACG}", "V")
        seq = seq.replace("{ACT}", "H")
        seq = seq.replace("{AGT}", "D")
        seq = seq.replace("{GATC}", "N")
        seq = seq.replace(" ", "")
        return seq
Referenced by amas.AMAS.FileParser.fasta_parse(), amas.AMAS.FileParser.nexus_interleaved_parse(), amas.AMAS.FileParser.nexus_parse(), amas.AMAS.FileParser.phylip_interleaved_parse(), and amas.AMAS.FileParser.phylip_parse().
Member Data Documentation
in_file
amas.AMAS.FileParser.in_file
Definition at line 542 of file AMAS.py.
Referenced by amas.AMAS.FileHandler.__exit__(), amas.AMAS.Alignment.get_aln_input(), and amas.AMAS.Alignment.get_name().
in_file_lines
amas.AMAS.FileParser.in_file_lines
Definition at line 544 of file AMAS.py.
Referenced by amas.AMAS.FileParser.fasta_parse(), amas.AMAS.FileParser.nexus_interleaved_parse(), amas.AMAS.FileParser.nexus_parse(), amas.AMAS.FileParser.partitions_parse(), amas.AMAS.FileParser.phylip_interleaved_parse(), and amas.AMAS.FileParser.phylip_parse().
The documentation for this class was generated from the following file:
amas/AMAS.py