AMAS_JGLAHE: amas.AMAS.AminoAcidAlignment Class Reference
amas.AMAS.AminoAcidAlignment Class Reference
Public Member Functions
get_summary (self)
get_taxa_summary (self)
Static Public Attributes
list alphabet = ["A", "C", "D", "E", "F", "G", "H", "I", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "V", "W", "Y", "B", "J", "Z", "X", ".", "*", "-", "?"]
list missing_ambiguous_chars = ["B", "J", "Z", "X", ".", "*", "-", "?"]
list missing_chars = ["X", ".", "*", "-", "?"]
list non_alphabet = ["O"]
Detailed Description
Alphabets specific to amino acid alignments
Definition at line 1085 of file AMAS.py.
Member Function Documentation
get_summary()
amas.AMAS.AminoAcidAlignment.get_summary (self)
Definition at line 1093 of file AMAS.py.
    def get_summary(self):
        # get alignment summary specific to amino acids
        data = self.summarize_alignment()
        new_data = data + list(self.get_char_summary()[1])
        return new_data
References amas.AMAS.Alignment.get_char_summary(), and amas.AMAS.Alignment.summarize_alignment().
get_taxa_summary()
amas.AMAS.AminoAcidAlignment.get_taxa_summary (self)
Definition at line 1099 of file AMAS.py.
    def get_taxa_summary(self):
        # get per-taxon/sequence alignment summary specific to amino acids
        data = self.summarize_alignment_by_taxa()
        aa_summary = (data, self.get_taxon_char_summary())
        zipped_list = list(zip(*aa_summary))
        new_data = [list(data_tupl) + chars for data_tupl, chars in zipped_list]
        return new_data
References amas.AMAS.Alignment.get_taxon_char_summary(), and amas.AMAS.Alignment.summarize_alignment_by_taxa().
Member Data Documentation
alphabet
list amas.AMAS.AminoAcidAlignment.alphabet = ["A", "C", "D", "E", "F", "G", "H", "I", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "V", "W", "Y", "B", "J", "Z", "X", ".", "*", "-", "?"] static
Definition at line 1088 of file AMAS.py.
Referenced by amas.AMAS.Alignment.append_count(), amas.AMAS.Alignment.get_char_summary(), and amas.AMAS.Alignment.get_counts_from_seq().
missing_ambiguous_chars
list amas.AMAS.AminoAcidAlignment.missing_ambiguous_chars = ["B", "J", "Z", "X", ".", "*", "-", "?"] static
Definition at line 1089 of file AMAS.py.
Referenced by amas.AMAS.Alignment.get_site_no_missing_ambiguous().
missing_chars
list amas.AMAS.AminoAcidAlignment.missing_chars = ["X", ".", "*", "-", "?"] static
Definition at line 1090 of file AMAS.py.
Referenced by amas.AMAS.Alignment.get_missing_from_seq(), and amas.AMAS.Alignment.replace_missing().
non_alphabet
list amas.AMAS.AminoAcidAlignment.non_alphabet = ["O"] static
Definition at line 1091 of file AMAS.py.
The documentation for this class was generated from the following file:
amas/AMAS.py