AMAS_JGLAHE: amas.AMAS Namespace Reference
amas.AMAS Namespace Reference
Classes
class Alignment
class AminoAcidAlignment
class DNAAlignment
class FileHandler
class FileParser
class MetaAlignment
class ParsedArgs
Functions
proportion (x)
main ()
run ()
Detailed Description
This stand-alone program allows manipulations of multiple sequence
alignments. It supports sequential FASTA, PHYLIP, NEXUS, and interleaved PHYLIP
and NEXUS formats for DNA and aino acid sequences. It can print summary statistics,
convert among formats, and concatenate alignments.
Current statistics include the number of taxa, alignment length, total number
of matrix cells, overall number of undetermined characters, percent of missing
data, AT and GC contents (for DNA alignments), number and proportion of
variable sites, number and proportion of parsimony informative sites,
and counts of all characters present in the relevant (nucleotide or amino acid) alphabet.
Function Documentation
main()
amas.AMAS.main ()
Definition at line 2361 of file AMAS.py.
def main():
    # initialize parsed arguments and meta alignment objects
    kwargs = run()
    meta_aln = MetaAlignment(**kwargs)
    if meta_aln.command == "summary":
        meta_aln.write_summaries(kwargs["summary_out"])
    if meta_aln.by_taxon_summary:
        print("Printing taxon summaries")
        meta_aln.write_taxa_summaries()
    if meta_aln.command == "convert":
        meta_aln.write_out("convert", kwargs["out_format"])
    if meta_aln.command == "concat":
        meta_aln.write_out("concat", kwargs["out_format"])
        meta_aln.write_partitions(kwargs["concat_part"], kwargs["part_format"], kwargs["data_type"], kwargs["codons"])
    if meta_aln.command == "replicate":
        meta_aln.write_out("replicate", kwargs["out_format"])
    if meta_aln.command == "split":
        meta_aln.write_out("split", kwargs["out_format"])
    if meta_aln.command == "remove":
        meta_aln.write_out("remove", kwargs["out_format"])
    if meta_aln.command == "translate":
        meta_aln.write_out("translate", kwargs["out_format"])
    if meta_aln.command == "trim":
        meta_aln.write_out("trim", kwargs["out_format"])
    if meta_aln.command == "metapartitions":
        # `metapartitions` is essentially `split` + `concat`. Currently you can't set an out_format:
        # it's automatically set to match the in_format because the intermediate `split` outputs become
        # the 'new' in_files for the `concat` operation, and then calling either:
        #  -> AminoAcidAlignment(Alignment.__init__(self, in_file, in_format, data_type))
        #  -> DNAAlignment(Alignment.__init__(self, in_file, in_format, data_type))
        # through MetaAlignment.get_alignment_object(alignment, self.in_format, self.data_type)
        meta_aln.write_out("metapartitions", kwargs["in_format"])
        meta_aln.write_partitions(kwargs["concat_part"], kwargs["part_format"], kwargs["data_type"], "none")
        # meta_aln.write_out("translate", kwargs["out_format"])
References amas.AMAS.run().
Referenced by amas.AMAS.run().
proportion()
amas.AMAS.proportion (x)
Definition at line 43 of file AMAS.py.
def proportion(x):
    # needed to prevent input of invalid floats in trim mode
    x = float(x)
    if x < 0.0 or x > 1.0:
        raise argparse.ArgumentTypeError("%r not in range [0.0, 1.0]" % (x,))
    return x
run()
amas.AMAS.run ()
Definition at line 2400 of file AMAS.py.
def run():
    # initialize parsed arguments
    config = ParsedArgs()
    # get arguments
    config_dict = config.get_args_dict()
    return config_dict
References amas.AMAS.main().
Referenced by amas.AMAS.main().